'use strict';
const titles=['Vorwissen','Gase entdecken','Hofmann-Apparat zur Wasserzersetzung','Elektrolyse erklären','Reaktionsgleichungen','Zelle untersuchen','Anode vergrößern','Ladung transportieren','Kathode vergrößern','Katalyse verstehen','Prozesse vergleichen','Üben & sichern'];
let current=0,dispose=()=>{};const lesson=document.getElementById('lesson'),answers={},revealed=new Set(),completed=new Set(),drafts={};
const Q={
redox:['Ein Teilchen gibt Elektronen ab. Wie heißt dieser Vorgang?',['Oxidation','Reduktion','Protonenübertragung'],0,'Oxidation bedeutet Elektronenabgabe.',''],
preReduction:['Ein Teilchen nimmt Elektronen auf. Wie heißt dieser Vorgang?',['Oxidation','Reduktion','Elektrolyse'],1,'Reduktion bedeutet Elektronenaufnahme.',''],
preCathode:['Welche Reaktion findet an einer Kathode statt?',['Oxidation','Reduktion','Verbrennung'],1,'An der Kathode findet die Reduktion statt.',''],
preEnergy:['Welche Energieumwandlung findet in einer galvanischen Zelle statt?',['chemische Energie → elektrische Energie','elektrische Energie → chemische Energie','Wärmeenergie → chemische Energie'],0,'Eine galvanische Zelle wandelt chemische in elektrische Energie um.',''],
preOxNumber:['Welche Oxidationszahl haben die Atome in H₂ und O₂?',['jeweils 0','jeweils +I','H: +I; O: −II'],0,'Atome in elementaren Stoffen haben die Oxidationszahl 0.',''],
products:['Welche beiden Gase erwartest du bei der Zerlegung von Wasser?',['H₂ und O₂','H₂ und CO₂','O₂ und N₂'],0,'Es entstehen Wasserstoff und Sauerstoff.',''],
ratio:['Wie verhalten sich die gesammelten Gasvolumina A : B?',['1 : 1','2 : 1','1 : 2'],1,'Es gilt H₂ : O₂ = 2 : 1.',''],
electrode:['Wasserstoff entsteht durch Aufnahme von Elektronen. An welcher Elektrode geschieht das?',['Anode · Pluspol','Kathode · Minuspol','Kathode · Pluspol'],1,'<strong>Kathode</strong> bedeutet Reduktion. Die Spannungsquelle liefert Elektronen am <strong>Minuspol</strong>.','Beachte, dass bei der Elektrolyse die Pole vertauscht sind.'],
fuel:['Was bildet die Brennstoffzelle aus H₂ und O₂?',['Wasser','Oxoniumionen als Endprodukt','Ein neues Metall'],0,'Die Brennstoffzelle bildet Wasser. Dabei werden elektrische Energie und Wärme abgegeben.',''],
hydrogen:['Welche Änderung der Oxidationszahl beschreibt H₂ → H⁺?',['0 → +I; Elektronenabgabe','+I → 0; Elektronenaufnahme','0 → −I; Elektronenaufnahme'],0,'H wird von 0 zu +I oxidiert.',''],
transport:['Welche Wege führen in der PEM-Brennstoffzelle von der Anode zur Kathode?',['H⁺ durch die Membran; e⁻ außen durch den Verbraucher','e⁻ durch die Membran; H⁺ außen durch den Verbraucher','Beide durch die Membran'],0,'H⁺ passiert die Membran; e⁻ fließt außen durch den Verbraucher.',''],
open:['Was erwartest du nach dem Öffnen des Stromkreises?',['Der dauerhafte Stoffumsatz stoppt.','Die Elektronen nehmen stattdessen die Membran.','Es entsteht dauerhaft mehr Wasser.'],0,'Ohne geschlossenen Stromkreis stoppt der dauerhafte Stoffumsatz.',''],
oxygen:['H hat in H₂O die Oxidationszahl +I. Welche Oxidationszahl hat O?',['−II','0','+II'],0,'In Wasser hat Sauerstoff die Oxidationszahl −II.',''],
need:['Wie viele Elektronen nimmt ein O₂-Molekül insgesamt auf?',['2','4','8'],1,'Ein O₂-Molekül nimmt formal vier Elektronen auf.',''],
cat:['Warum nennt man die Katalyse hier heterogen?',['Katalysator und Reaktanden liegen in verschiedenen Phasen vor.','Die Reaktion erzeugt verschiedene Produkte.','Der Katalysator wird verbraucht.'],0,'Der feste Katalysator und die gasförmigen Reaktanden bilden verschiedene Phasen.',''],
homocat:['Was ist ein homogener Katalysator?',['Er liegt in derselben Phase wie die Reaktanden vor.','Er ist immer ein Feststoff.','Er wird vollständig verbraucht.'],0,'Ein homogener Katalysator liegt in derselben Phase wie die Reaktanden vor.',''],
energy:['Welche Aussage beschreibt den Zyklus Strom → H₂ → Strom?',['Die gesamte eingesetzte Stromenergie kommt zurück.','Wegen Umwandlungsverlusten kommt weniger Stromenergie zurück.','Wasserstoff erzeugt zusätzliche Energie.'],1,'Wegen der Umwandlungsverluste wird weniger Stromenergie zurückgewonnen.',''],
test1:['Anode bedeutet immer …',['Oxidation','Pluspol','Reduktion'],0,'An der Anode findet die Oxidation statt.',''],
test2:['Wo entstehen in der PEM-Zelle die Wassermoleküle?',['An der Kathode','Im Verbraucher','An der Wasserstoffzufuhr'],0,'Wasser entsteht an der Kathode.',''],
test3:['Warum sind für zwei H₂O vier H⁺ nötig?',['Zwei Wassermoleküle enthalten vier H-Kerne.','Wasser hat die Ladung +4.','Jedes O-Atom braucht vier H-Kerne.'],0,'Zwei H₂O enthalten insgesamt vier H-Atome.',''],
test4:['Was bewirkt der Katalysator?',['Er ermöglicht einen Reaktionsweg mit geringerer Aktivierungsenergie.','Er erhöht die frei werdende Gesamtenergie.','Er liefert Elektronen und wird verbraucht.'],0,'Der Katalysator senkt die Aktivierungsenergie und wird regeneriert.',''],
test5:['Wie beurteilst du die Umweltwirkung von Wasserstoff?',['Nur anhand des Wassers als Nutzungsprodukt.','Auch anhand von Stromherkunft, Herstellung und Verlusten.','Wasserstoff ist immer klimaneutral.'],1,'Stromherkunft, Herstellung, Speicherung und Nutzung gehören zur Bewertung.','']
};
function shuffled(q){return q[1].map((text,index)=>({text,index})).sort(()=>Math.random()-.5);}
function ask(id,after=''){const q=Q[id],options=shuffled(q);return `<section class="task" data-quiz="${id}"><div class="task-label">DU BIST DRAN</div><h2>${q[0]}</h2><fieldset><legend class="sr-only">${q[0]}</legend>${options.map(o=>`<label class="choice"><input type="radio" name="${id}" value="${o.index}" ${answers[id]===o.index?'checked':''}>${o.text}</label>`).join('')}</fieldset><div class="controls"><button data-check="${id}">Prüfen</button>${id==='electrode'?`<button class="secondary" data-hint="${id}">Tipp</button>`:''}<button class="text-button" data-solve="${id}">Lösung ansehen</button></div><div class="feedback" aria-live="polite"></div>${after?`<div data-reveal="${id}" ${revealed.has(id)?'':'hidden'}>${after}</div>`:''}</section>`;}
function bindTasks(){document.querySelectorAll('[data-quiz]').forEach(box=>{const id=box.dataset.quiz,q=Q[id],f=box.querySelector('.feedback');box.querySelector('[data-check]').onclick=()=>{const sel=box.querySelector('input:checked');if(!sel){f.textContent='Wähle zuerst eine Antwort.';return;}answers[id]=Number(sel.value);if(answers[id]===q[2]){completed.add(id);reveal();f.className='feedback correct';f.innerHTML=q[3];}else{f.className='feedback incorrect';f.textContent='Noch nicht richtig.';}progress();};const hint=box.querySelector('[data-hint]');if(hint)hint.onclick=()=>{f.className='feedback';f.textContent=q[4];};box.querySelector('[data-solve]').onclick=()=>{reveal();f.className='feedback';f.innerHTML=`Lösung: ${q[1][q[2]]}.`;};function reveal(){revealed.add(id);const r=box.querySelector('[data-reveal]');if(r)r.hidden=false;}});}
function balance(id,type){const eq=type==='anode'?'<span>2 H₂ →</span><label><input data-num="H" type="number" min="0" max="12"> H⁺ +</label><label><input data-num="E" type="number" min="0" max="12"> e⁻</label>':'<span>O₂ +</span><label><input data-num="H" type="number" min="0" max="12"> H⁺ +</label><label><input data-num="E" type="number" min="0" max="12"> e⁻ →</label><label><input data-num="W" type="number" min="0" max="12"> H₂O</label>';return `<section class="task" data-balance="${id}" data-type="${type}"><div class="task-label">GLEICHUNG BAUEN</div><h2>${type==='anode'?'Ergänze die Zahlen der Anodenreaktion.':'Ergänze die Zahlen der Kathodenreaktion.'}</h2><div class="controls equation">${eq}</div><div class="controls"><button data-bcheck>Prüfen</button><button class="text-button" data-bsolve>Lösung ansehen</button></div><div class="feedback" aria-live="polite"></div></section>`;}
function bindBalances(){document.querySelectorAll('[data-balance]').forEach(box=>{const id=box.dataset.balance,f=box.querySelector('.feedback'),inputs=[...box.querySelectorAll('input')],anode=box.dataset.type==='anode';inputs.forEach(x=>{x.value=drafts[id]?.[x.dataset.num]??'';x.oninput=()=>drafts[id]=Object.fromEntries(inputs.map(x=>[x.dataset.num,x.value]));});box.querySelector('[data-bsolve]').onclick=()=>{inputs.forEach(x=>x.value=x.dataset.num==='W'?2:4);inputs[0].oninput();f.textContent=anode?'2 H₂ → 4 H⁺ + 4 e⁻':'O₂ + 4 H⁺ + 4 e⁻ → 2 H₂O';};box.querySelector('[data-bcheck]').onclick=()=>{if(inputs.some(x=>x.value==='')){f.textContent='Trage alle Zahlen ein.';return;}const v=Object.fromEntries(inputs.map(x=>[x.dataset.num,Number(x.value)]));if(v.H===4&&v.E===4&&(anode||v.W===2)){completed.add(id);f.className='feedback correct';f.textContent='Die Gleichung ist ausgeglichen.';progress();}else{f.className='feedback incorrect';f.textContent='Die Gleichung ist noch nicht ausgeglichen.';}};});}
function sim(view='overview',showNote=true){return `<div class="lab fuel-lab"><div class="lab-top"><span>PEM-BRENNSTOFFZELLE</span><span class="model-label">Teilchenmodell</span></div><div class="controls view-controls"><button data-view="overview" class="secondary">Gesamtansicht</button><button data-view="anode" class="secondary">⊕ Anode vergrößern</button><button data-view="cathode" class="secondary">⊕ Kathode vergrößern</button></div><canvas id="fuel" role="img"></canvas><div class="legend"><span><i class="swatch hyd"></i>H / H⁺</span><span><i class="swatch oxy"></i>O</span><span><i class="swatch electron"></i>e⁻</span></div></div><div class="controls"><button id="play">Ablauf abspielen</button><button id="restart" class="secondary">Von vorn</button><label><input id="circuit" type="checkbox"> Stromkreis offen</label></div><div class="steps" id="stages"></div><div class="reaction-detail box" id="reaction" aria-live="polite"></div>${showNote?'<p class="quiet">Klicke in der Gesamtansicht auf eine Elektrode oder nutze die Vergrößerungsbuttons. H⁺ steht für protonische Ladung im wasserhaltigen Medium.</p>':''}<span id="initialview" data-initial="${view}" hidden></span>`;}
function reactionBuilder(){return `<section class="task reaction-builder"><div class="task-label">DRAG & DROP</div><p>Ziehe die Stoffe auf die richtige Seite. Gib die Koeffizienten anschließend selbst ein.</p><div class="species-bank" aria-label="Stoffkarten">${['H₂O','H⁺','e⁻','H₂','O₂'].map(s=>`<button class="species" draggable="true" data-species="${s}">${s}</button>`).join('')}</div>${equationLane('Anode','anodeEq')}${equationLane('Kathode','cathodeEq')}<div class="controls"><button id="reactionCheck">Prüfen</button><button class="secondary" id="reactionReset">Zurücksetzen</button><button class="text-button" id="reactionSolve">Lösung ansehen</button></div><div id="reactionFeedback" class="feedback" aria-live="polite"></div></section>`;}
function equationLane(label,id){return `<div class="equation-lane" data-equation="${id}"><h2>${label}</h2><div class="equation-drop" data-side="left" tabindex="0" aria-label="Edukte der ${label}"></div><span class="reaction-arrow">→</span><div class="equation-drop" data-side="right" tabindex="0" aria-label="Produkte der ${label}"></div></div>`;}
function bindReactionBuilder(){let selected='',data={cathodeEq:{left:[],right:[]},anodeEq:{left:[],right:[]}};const render=()=>document.querySelectorAll('.equation-drop').forEach(z=>{const eq=z.closest('[data-equation]').dataset.equation,side=z.dataset.side;z.innerHTML=data[eq][side].length?data[eq][side].map((s,i)=>`<span class="placed"><input type="number" min="1" max="9" value="${s.n}" data-eq="${eq}" data-side="${side}" data-index="${i}" aria-label="Koeffizient vor ${s.s}"><b>${s.s}</b><button data-remove="${eq}|${side}|${i}" aria-label="${s.s} entfernen">×</button></span>`).join('<span> + </span>'):'<span class="drop-label">Hier ablegen</span>';});
document.querySelectorAll('.species').forEach(b=>{b.ondragstart=e=>e.dataTransfer.setData('text/plain',b.dataset.species);b.onclick=()=>{selected=b.dataset.species;document.querySelectorAll('.species').forEach(x=>x.classList.toggle('selected',x===b));};});
document.querySelectorAll('.equation-drop').forEach(z=>{z.ondragover=e=>e.preventDefault();z.ondrop=e=>{e.preventDefault();add(z,e.dataTransfer.getData('text/plain'));};z.onclick=e=>{const remove=e.target.closest('[data-remove]');if(remove){const [eq,side,i]=remove.dataset.remove.split('|');data[eq][side].splice(Number(i),1);render();return;}if(selected)add(z,selected);};z.onkeydown=e=>{if((e.key==='Enter'||e.key===' ')&&selected){e.preventDefault();add(z,selected);}};});
function add(z,s){const eq=z.closest('[data-equation]').dataset.equation;data[eq][z.dataset.side].push({s,n:''});selected='';document.querySelectorAll('.species').forEach(x=>x.classList.remove('selected'));render();}
document.querySelector('.reaction-builder').oninput=e=>{if(!e.target.matches('[data-eq]'))return;data[e.target.dataset.eq][e.target.dataset.side][Number(e.target.dataset.index)].n=e.target.value;};
const expected={cathodeEq:{left:{'H⁺':4,'e⁻':4},right:{'H₂':2}},anodeEq:{left:{'H₂O':2},right:{'O₂':1,'H⁺':4,'e⁻':4}}};
function sameComposition(cards,target){const got={};cards.forEach(({s,n})=>got[s]=(got[s]||0)+Number(n));const substances=new Set([...Object.keys(got),...Object.keys(target)]);return [...substances].every(s=>(got[s]||0)===(target[s]||0));}
function valid(){return Object.keys(expected).every(eq=>['left','right'].every(side=>sameComposition(data[eq][side],expected[eq][side])));}
document.getElementById('reactionCheck').onclick=()=>{const f=document.getElementById('reactionFeedback');if(valid()){completed.add('reactionbuilder');f.className='feedback correct';f.textContent='Beide Teilgleichungen sind richtig aufgebaut und ausgeglichen.';progress();}else{f.className='feedback incorrect';f.textContent='Mindestens eine Teilgleichung ist noch nicht richtig.';}};
document.getElementById('reactionReset').onclick=()=>{data={cathodeEq:{left:[],right:[]},anodeEq:{left:[],right:[]}};render();document.getElementById('reactionFeedback').textContent='';};
document.getElementById('reactionSolve').onclick=()=>{data={cathodeEq:{left:[{s:'H⁺',n:4},{s:'e⁻',n:4}],right:[{s:'H₂',n:2}]},anodeEq:{left:[{s:'H₂O',n:2}],right:[{s:'O₂',n:1},{s:'H⁺',n:4},{s:'e⁻',n:4}]}};render();document.getElementById('reactionFeedback').textContent='Anode: 2 H₂O → O₂ + 4 H⁺ + 4 e⁻. Kathode: 4 H⁺ + 4 e⁻ → 2 H₂.';};render();}
const pages=[
()=>`<p class="eyebrow">01 · ERINNERN</p><h1>Was weißt du schon?</h1><p class="lead">Du untersuchst, wie Wasser mit Strom zerlegt wird und wie aus den Gasen wieder Strom gewonnen werden kann.</p>${ask('redox','<div class="box"><strong>Anode = Oxidation · Kathode = Reduktion</strong></div>')}${ask('preReduction')}${ask('preCathode')}${ask('preEnergy')}${ask('preOxNumber')}`,
()=>`<p class="eyebrow">02 · VERMUTEN</p><h1>Welche Gase stecken im Wasser?</h1><p>Eine Spannungsquelle zerlegt Wasser. Der Hofmann-Apparat sammelt die Gase getrennt.</p>${ask('products','<div class="box"><p>Wasserstoff: Knallgasprobe. Sauerstoff: Glimmspanprobe.</p></div>')}`,
()=>`<p class="eyebrow">03 · BEOBACHTEN</p><h1>Warum sind die Mengen verschieden?</h1><p>Starte die Elektrolyse oder bewege den Regler. Vergleiche die gelben Gasräume oben.</p><div class="lab"><canvas id="hof" role="img"></canvas><label for="gasamount">Fortschritt: <output id="gasvalue">0</output> Modell-Einheiten</label><input id="gasamount" type="range" min="0" max="10" value="0"><div id="gasstatus" aria-live="polite"></div></div>${ask('ratio','<p class="equation">2 H₂O → 2 H₂ + O₂</p>')}`,
()=>`<p class="eyebrow">04 · ZUORDNEN</p><h1>Was passiert an den Elektroden?</h1><p>Wasserstoff entsteht durch Elektronenaufnahme.</p>${ask('electrode')}`,
()=>`<p class="eyebrow">05 · AUFSTELLEN</p><h1>Reaktionsgleichungen</h1><p>Erstelle die beiden Teilgleichungen der Wasserelektrolyse. Die Stoffkarten enthalten bewusst keine Koeffizienten.</p>${reactionBuilder()}`,
()=>`<p class="eyebrow">06 · ENTDECKEN</p><h1>Die Brennstoffzelle untersuchen</h1><p><strong>PEM</strong> bedeutet <strong>Proton Exchange Membrane</strong>, also Protonenaustauschmembran.</p><div class="box"><p>Mit den im Hofmann-Apparat hergestellten Gasen Sauerstoff und Wasserstoff kann eine Brennstoffzelle als galvanische Zelle chemische in elektrische Energie umwandeln.</p><p><strong>Aufbau:</strong> Anode und Kathode liegen beiderseits der PEM. Wasserstoff gelangt zur Anode, Sauerstoff zur Kathode; außen verbindet ein Leiter mit Verbraucher beide Elektroden.</p></div>${ask('fuel')}<p>Untersuche die Gesamtansicht und vergrößere beide Elektroden.</p>${sim()}`,
()=>`<p class="eyebrow">07 · ANODE</p><h1>Wasserstoff gibt Elektronen ab.</h1><p>Die Anode ist automatisch vergrößert. Beobachte, wie Wasserstoffgas zunächst den Platin-Katalysator erreicht. Erst an der Oberfläche wird die H–H-Bindung getrennt und die Wasserstoffatome geben Elektronen ab.</p>${sim('anode',false)}${ask('hydrogen')}${balance('anodebalance','anode')}`,
()=>`<p class="eyebrow">08 · TRANSPORT</p><h1>Zwei Wege gehören zusammen.</h1><p>Teste in der Gesamtansicht den Schritt „Transport“.</p>${sim()}${ask('transport')}${ask('open')}`,
()=>`<p class="eyebrow">09 · KATHODE</p><h1>Sauerstoff wird zu Wasser reduziert.</h1><p>Die Kathode ist automatisch vergrößert. Beobachte zuerst, wie O₂ zur Kathode gelangt und dort Elektronen aufnimmt. Danach reagieren jeweils zwei Protonen mit einem O²⁻-Teilchen zu einem Wassermolekül.</p>${sim('cathode',false)}${ask('oxygen')}${ask('need')}${balance('cathodebalance','cathode')}`,
()=>`<p class="eyebrow">10 · KATALYSE</p><h1>Die Oberfläche hilft der Reaktion.</h1><button id="catDefinition" class="secondary">Was ist ein Katalysator?</button><div id="catDefinitionText" class="box" hidden>Ein Katalysator ermöglicht einen Reaktionsweg mit geringerer Aktivierungsenergie und wird nach der Reaktion regeneriert.</div><div class="catalyst-model"><canvas id="catcanvas" role="img" aria-label="Wasserstoff reagiert schrittweise an einer Platinoberfläche."></canvas><div id="catdetail" aria-live="polite"></div><div class="controls"><button id="catnext">Nächster Vorgang →</button><button class="secondary" id="catreset">Von vorn</button></div></div><section class="task"><div class="task-label">ABLAUF ORDNEN</div><h2>Ordne die Oberflächenvorgänge.</h2><div id="catorder"></div><button id="ordercheck">Prüfen</button><div id="orderfeedback" class="feedback" aria-live="polite"></div></section>${ask('cat')}${ask('homocat')}`,
()=>`<p class="eyebrow">11 · VERGLEICHEN</p><h1>Was bleibt, was kehrt sich um?</h1><div class="box"><p class="equation">Anode: 2 H₂ → 4 H⁺ + 4 e⁻</p><p class="equation">Kathode: O₂ + 4 H⁺ + 4 e⁻ → 2 H₂O</p></div><p>Welche Teilchen lassen sich beim Addieren kürzen?</p><section class="task"><select id="cancel"><option value="">Wählen</option><option value="right">H⁺ und e⁻</option><option>H₂ und O₂</option><option>H₂O und e⁻</option></select><button id="cancelcheck">Prüfen</button><div id="cancelfeedback" class="feedback"></div></section><section class="task"><div class="tablewrap"><table><thead><tr><th>Merkmal</th><th>Hofmann-Apparat</th><th>PEM-Brennstoffzelle</th></tr></thead><tbody>${compareRow('Edukte','eductE',['Wasser','H₂ und O₂'],'eductF',['Wasser','H₂ und O₂'])}${compareRow('Produkte','productE',['H₂ und O₂','Wasser'],'productF',['H₂ und O₂','Wasser'])}${compareRow('Anode','poleE',['Pluspol','Minuspol'],'poleF',['Pluspol','Minuspol'])}${compareRow('Kathode','cathE',['Pluspol','Minuspol'],'cathF',['Pluspol','Minuspol'])}${compareRow('Energie','energyE',['elektrisch → chemisch','chemisch → elektrisch'],'energyF',['elektrisch → chemisch','chemisch → elektrisch'])}${compareRow('Betrieb','driveE',['äußere Spannung nötig','liefert Strom'],'driveF',['äußere Spannung nötig','liefert Strom'])}</tbody></table></div><button id="comparecheck">Prüfen</button><div id="comparefeedback" class="feedback"></div></section>${ask('energy')}`,
()=>`<p class="eyebrow">12 · ÜBEN</p><h1>Erkläre es selbst.</h1>${['test1','test2','test3','test4','test5'].map(ask).join('')}<div class="box"><strong>Abschluss:</strong> Zeichne die Zelle und ergänze Ladungswege, Teilgleichungen und Katalysator.</div><details><summary>Quellen und Modellgrenzen</summary><p><a href="https://www.energy.gov/cmei/fuels/parts-fuel-cell">DOE: PEM-Zelle und Katalysator</a> · <a href="https://www.energy.gov/cmei/fuels/hydrogen-production-electrolysis">DOE: Elektrolyse</a> · <a href="https://lehrplannavigator.nrw.de/system/files/media/document/file/gost_klp_ch_2022_06_07.pdf">NRW-Kernlehrplan Chemie</a></p><p>Die Animation zeigt die Teilvorgänge nacheinander.</p></details>`
];
function pick(id,options){return `<select id="${id}"><option value="">Wählen</option>${options.map((s,i)=>`<option value="${i}">${s}</option>`).join('')}</select>`;}
function compareRow(label,idE,optE,idF,optF){return `<tr><th>${label}</th><td>${pick(idE,optE)}</td><td>${pick(idF,optF)}</td></tr>`;}
document.getElementById('nav').innerHTML=titles.map((t,i)=>`<button data-page="${i}"><span>${String(i+1).padStart(2,'0')}</span>${t}</button>`).join('');document.querySelectorAll('[data-page]').forEach(b=>b.onclick=()=>show(Number(b.dataset.page),true));document.getElementById('back').onclick=()=>show(current-1,true);document.getElementById('next').onclick=()=>show(current+1,true);
function progress(){document.getElementById('progress').textContent=`${completed.size} von ${Object.keys(Q).length+6} Aufgaben richtig geprüft`;}
function show(i,scroll=false){dispose();dispose=()=>{};current=Math.max(0,Math.min(titles.length-1,i));lesson.innerHTML=pages[current]();document.querySelectorAll('[data-page]').forEach(b=>Number(b.dataset.page)===current?b.setAttribute('aria-current','step'):b.removeAttribute('aria-current'));document.getElementById('back').disabled=current===0;document.getElementById('next').disabled=current===titles.length-1;bindTasks();bindBalances();if(document.getElementById('hof'))initHof();if(document.getElementById('fuel'))initFuel();if(current===4)bindReactionBuilder();if(current===9)initCatalyst();if(current===10)initCompare();progress();if(scroll){const h=lesson.querySelector('h1');h.tabIndex=-1;h.focus({preventScroll:true});document.getElementById('content').scrollIntoView({block:'start'});}}
function initCatalyst(){let stage=0;const notes=['1 · H₂ nähert sich der Platinoberfläche.','2 · H₂ lagert sich an; die H–H-Bindung wird getrennt.','3 · Jedes adsorbierte H-Atom gibt ein Elektron an das Metall ab und wird zu H⁺.','4 · H⁺ wandert zum Elektrolyten und zur PEM; e⁻ fließt durch das Metall in den äußeren Stromkreis. Platin steht erneut bereit.'],simulator=initCatalystAnimation();function draw(){document.getElementById('catdetail').textContent=notes[stage];document.getElementById('catnext').disabled=stage===3;simulator.set(stage);}document.getElementById('catDefinition').onclick=()=>document.getElementById('catDefinitionText').hidden=false;document.getElementById('catnext').onclick=()=>{stage++;draw();};document.getElementById('catreset').onclick=()=>{stage=0;draw();};document.getElementById('catorder').innerHTML=[1,2,3].map(i=>`<label class="order-row">${i}. <select><option value="">Wählen</option><option value="release">Produkte lösen sich ab</option><option value="react">Reaktion an der Oberfläche</option><option value="attach">Reaktanden lagern sich an</option></select></label>`).join('');document.getElementById('ordercheck').onclick=()=>{const val=[...document.querySelectorAll('#catorder select')].map(s=>s.value),f=document.getElementById('orderfeedback');if(val.join(',')==='attach,react,release'){completed.add('catorder');f.className='feedback correct';f.textContent='Die Reihenfolge ist richtig.';progress();}else{f.className='feedback incorrect';f.textContent='Die Reihenfolge ist noch nicht richtig.';}};const prior=dispose;dispose=()=>{simulator.destroy();prior();};draw();}
function initCompare(){document.getElementById('cancelcheck').onclick=()=>{const f=document.getElementById('cancelfeedback');if(document.getElementById('cancel').value==='right'){completed.add('cancel');f.className='feedback correct';f.textContent='H⁺ und e⁻ kürzen sich heraus.';progress();}else{f.className='feedback incorrect';f.textContent='Noch nicht richtig.';}};document.getElementById('comparecheck').onclick=()=>{const right={eductE:'0',eductF:'1',productE:'0',productF:'1',poleE:'0',poleF:'1',cathE:'1',cathF:'0',energyE:'0',energyF:'1',driveE:'0',driveF:'1'},bad=Object.keys(right).some(id=>document.getElementById(id).value!==right[id]),f=document.getElementById('comparefeedback');if(!bad){completed.add('compare');f.className='feedback correct';f.textContent='Der Vergleich ist vollständig richtig.';progress();}else{f.className='feedback incorrect';f.textContent='Mindestens eine Zuordnung ist noch nicht richtig.';}};}
