function setupCanvas(id,paint,height=390){const canvas=document.getElementById(id),ctx=canvas.getContext('2d');let width=700;function draw(){const d=window.devicePixelRatio||1;width=canvas.clientWidth;canvas.width=width*d;canvas.height=height*d;ctx.setTransform(d,0,0,d,0,0);paint(ctx,width,height);}const ro=new ResizeObserver(draw);ro.observe(canvas);const prior=dispose;dispose=()=>{ro.disconnect();prior();};draw();return draw;}
const C={hyd:'#126eaa',oxy:'#b53536',el:'#83530c',line:'#7796aa',text:'#163247'};
function text(c,s,x,y,align='center',size=14){c.fillStyle=C.text;c.font=`${size}px system-ui`;c.textAlign=align;c.fillText(s,x,y);}
function path(c,points,color=C.line,width=2){c.strokeStyle=color;c.lineWidth=width;c.beginPath();points.forEach((p,i)=>i?c.lineTo(...p):c.moveTo(...p));c.stroke();}
function atom(c,x,y,kind,label=''){c.fillStyle=kind==='O'?C.oxy:kind==='e'?C.el:C.hyd;c.beginPath();c.arc(x,y,kind==='O'?10:kind==='e'?9:7,0,Math.PI*2);c.fill();if(label){c.fillStyle='#fff';c.font='13px system-ui';c.textAlign='center';c.fillText(label,x,y+4);}}
function molecule(c,x,y,type){if(type==='H2'){path(c,[[x-9,y],[x+9,y]]);atom(c,x-9,y,'H');atom(c,x+9,y,'H');}else if(type==='O2'){path(c,[[x-12,y],[x+12,y]]);atom(c,x-12,y,'O');atom(c,x+12,y,'O');}else{path(c,[[x-13,y+12],[x,y],[x+13,y+12]]);atom(c,x,y,'O');atom(c,x-13,y+12,'H');atom(c,x+13,y+12,'H');}}
function initHof(){
const slider=document.getElementById('gasamount'),canvas=document.getElementById('hof');canvas.style.height='460px';
slider.step='0.1';let playing=false,n=Number(slider.value),frame=0,last=0,clock=0,destroyed=false;
const controls=document.createElement('div');controls.className='controls';controls.innerHTML='<button id="hofplay">Elektrolyse starten</button><button id="hofreset" class="secondary">Zurücksetzen</button>';
canvas.insertAdjacentElement('afterend',controls);
const legend=document.createElement('div');legend.className='legend';legend.innerHTML='<span><i class="swatch" style="background:#eab94a"></i>Gesammeltes Gas (oben)</span><span><i class="swatch" style="background:#86bddc"></i>Elektrolytflüssigkeit (unten)</span>';
controls.insertAdjacentElement('afterend',legend);legend.insertAdjacentHTML('afterend','<p class="quiet">Die Zahlen und Skalen messen das Gas oben, nicht die Flüssigkeit darunter. Volumenmodell bei gleichem Druck und gleicher Temperatur; Druckunterschiede im Apparat sind ausgeblendet.</p>');
const play=document.getElementById('hofplay'),fmt=v=>Number(v.toFixed(1)).toLocaleString('de-DE');
const draw=setupCanvas('hof',(c,w)=>{
const left=w*.22,right=w*.78,mid=w*.5,tube=Math.min(68,w*.16),reservoir=Math.min(55,w*.12),top=80,bottom=320;
text(c,'Gasraum A',left,22);text(c,'Gasraum B',right,22);text(c,'Vorrat',mid,56);
path(c,[[left,bottom],[left,342],[right,342],[right,bottom]],'#86bddc',12);
const reservoirLevel=132-n*4;c.fillStyle='#b6d9ee';c.fillRect(mid-reservoir/2,reservoirLevel,reservoir,210-reservoirLevel+132);
path(c,[[mid-reservoir/2,74],[mid-reservoir/2,348],[mid+reservoir/2,348],[mid+reservoir/2,74]]);path(c,[[mid-reservoir/2,reservoirLevel],[mid+reservoir/2,reservoirLevel]],'#548cac',2);
[left,right].forEach((x,i)=>{
const amount=n*(i===0?2:1),gasHeight=amount*8,level=top+gasHeight;
const water=c.createLinearGradient(x-tube/2,0,x+tube/2,0);water.addColorStop(0,'#94c4e0');water.addColorStop(.5,'#c1e1f3');water.addColorStop(1,'#94c4e0');c.fillStyle=water;c.fillRect(x-tube/2,level,tube,bottom-level);
c.fillStyle='#f7cf69';c.fillRect(x-tube/2,top,tube,gasHeight);
path(c,[[x-tube/2,top],[x-tube/2,bottom],[x+tube/2,bottom],[x+tube/2,top],[x-tube/2,top]],'#54798f');
path(c,[[x,top],[x,37]],'#54798f');path(c,[[x-10,48],[x+10,48]],'#456b83',4);text(c,'zu',x,69,'center',12);
for(let value=0;value<=25;value+=5){const y=top+value*8;path(c,[[x+tube/2,y],[x+tube/2+6,y]],'#54798f',1);text(c,String(value),x+tube/2+10,y+4,'left',12);}
if(gasHeight>=24)text(c,'Gas',x,top+gasHeight/2+5);
path(c,[[x-tube/2,level],[x+tube/2,level]],'#9e6b0e',2);
electrode(c,x-5,bottom-28,10,28,'right',false);
if(n>0){const count=i===0?6:3;for(let j=0;j<count;j++){const phase=playing?(clock/1500+j/count)%1:(j+1)/(count+1),y=bottom-35-phase*(bottom-42-level);c.beginPath();c.arc(x+(j%2?6:-6),y,3,0,Math.PI*2);c.fillStyle='#f7cf69';c.fill();c.strokeStyle='#9e6b0e';c.lineWidth=1;c.stroke();}}
text(c,`${fmt(amount)} Vol.-Einh.`,x,377);text(c,i===0?'Minuspol':'Pluspol',x,402);
});
text(c,'Flüssigkeit',mid,370,'center',13);text(c,'Gasskalen: gleiche Rohrweite',mid,433,'center',12);text(c,'Einheiten auf beiden Seiten gleich',mid,453,'center',12);
canvas.setAttribute('aria-label',`Hofmann-Apparat: Gelber Gasraum A oben ${fmt(2*n)} Volumeneinheiten, gelber Gasraum B oben ${fmt(n)}. Blaue Flüssigkeit darunter. Beide Gasräume besitzen dieselbe Rohrweite und Skala.`);
},460);
function update(){slider.value=n.toFixed(1);document.getElementById('gasvalue').textContent=fmt(n);document.getElementById('gasstatus').textContent=`Gesammeltes Gas oben: A = ${fmt(2*n)} · B = ${fmt(n)} Volumeneinheiten`;play.textContent=playing?'Pause':'Elektrolyse starten';}
function tick(now){if(destroyed)return;const dt=last?Math.min(now-last,100):0;last=now;clock+=dt;if(playing){n=Math.min(10,n+dt/1500);if(n===10)playing=false;update();draw();if(playing)frame=requestAnimationFrame(tick);}}
play.onclick=()=>{cancelAnimationFrame(frame);playing=!playing;if(playing){if(n===10)n=0;last=0;frame=requestAnimationFrame(tick);}update();draw();};
document.getElementById('hofreset').onclick=()=>{playing=false;cancelAnimationFrame(frame);n=0;update();draw();};
slider.oninput=()=>{playing=false;cancelAnimationFrame(frame);n=Number(slider.value);update();draw();};
const prior=dispose;dispose=()=>{destroyed=true;cancelAnimationFrame(frame);prior();};update();draw();
}

const stageNames=['Edukte','Oxidation','Transport','Reduktion','Wasserbildung'];
const descriptions=[['Zwei H₂ und ein O₂','Die Gase erreichen getrennte Elektroden.'],['Anode −: Wasserstoff wird oxidiert','H₂ erreicht den Platin-Katalysator. Erst an der Oberfläche wird die H–H-Bindung getrennt; anschließend entstehen H⁺ und e⁻: 2 H₂ → 4 H⁺ + 4 e⁻.'],['Die Ladung nimmt zwei Wege','H⁺ passiert die Membran; e⁻ fließt außen durch den Verbraucher und bis in die Kathode.'],['Kathode +: Sauerstoff nimmt Elektronen auf','O₂ gelangt an die Kathode. Dort nimmt jedes Sauerstoffatom zwei Elektronen auf: O₂ + 4 e⁻ → 2 O²⁻.'],['Wasserbildung','Je zwei H⁺ reagieren an der Kathode mit einem O²⁻. Es entstehen zwei Wassermoleküle: 2 O²⁻ + 4 H⁺ → 2 H₂O.']];
function sphere(c,x,y,type,label='',r){r=r??(type==='O'?16:type==='e'?12:12);const color=type==='O'?C.oxy:type==='e'?C.el:C.hyd,g=c.createRadialGradient(x-r*.35,y-r*.4,r*.05,x,y,r);g.addColorStop(0,type==='O'?'#f49b91':type==='e'?'#d6a856':'#91d2fa');g.addColorStop(.6,color);g.addColorStop(1,type==='O'?'#812326':type==='e'?'#664009':'#0d456b');c.fillStyle=g;c.beginPath();c.arc(x,y,r,0,Math.PI*2);c.fill();if(label){c.fillStyle='#fff';c.font=`${type==='e'?11:14}px system-ui`;c.textAlign='center';c.fillText(label,x,y+4);}}
function oxidize(c,startX,startYs,d,hX,eX,ys,q,zoom){const contactX=(hX+eX)/2,approach=Math.min(1,q/.45),split=Math.max(0,Math.min(1,(q-.45)/.2)),separate=Math.max(0,Math.min(1,(q-.65)/.35)),hr=zoom?16:12,er=zoom?14:10;for(let k=0;k<2;k++){const sy=startYs[k];if(q<.45){pair(c,startX+(contactX-startX)*approach,sy,'H',zoom);continue;}const atoms=[];for(let j=0;j<2;j++){const i=k*2+j,startAtomX=contactX+(j?d:-d),surfaceY=sy+(ys[i]-sy)*split,x=startAtomX+(hX-startAtomX)*separate,y=surfaceY+(ys[i]-surfaceY)*separate;atoms.push([x,y]);sphere(c,x,y,'H',separate>.08?'+':'H',hr);if(separate>0){c.globalAlpha=separate;sphere(c,contactX+(eX-contactX)*separate,ys[i],'e','e⁻',er);c.globalAlpha=1;}}if(split<1)path(c,atoms,'#637e90',(1-split)*(zoom?4:3));}}
function pair(c,x,y,type,zoom=false){const d=zoom?22:13;path(c,[[x-d,y],[x+d,y]],'#637e90',zoom?4:3);sphere(c,x-d,y,type,type,zoom?22:undefined);sphere(c,x+d,y,type,type,zoom?22:undefined);}
function electrode(c,x,y,width,height,side='right',showCatalyst=true){const g=c.createLinearGradient(x,0,x+width,0);g.addColorStop(0,'#24465e');g.addColorStop(.5,'#7b9aaf');g.addColorStop(1,'#26485f');c.fillStyle=g;c.fillRect(x,y,width,height);if(!showCatalyst)return;const px=x+width*(side==='left'?.25:.75);for(let i=0;i<7;i++){c.fillStyle='#f0d18a';c.beginPath();c.arc(px,y+18+i*(height-36)/6,3,0,Math.PI*2);c.fill();}}
function arrow(c,x1,y1,x2,y2,color=C.line){path(c,[[x1,y1],[x2,y2]],color);const a=Math.atan2(y2-y1,x2-x1);path(c,[[x2-7*Math.cos(a-.55),y2-7*Math.sin(a-.55)],[x2,y2],[x2-7*Math.cos(a+.55),y2-7*Math.sin(a+.55)]],color);}
function wirePoint(L,R,y,q){if(q<.25)return [L,y-(y-65)*q/.25];if(q<.75)return [L+(R-L)*(q-.25)/.5,65];return [R,65+(y-65)*(q-.75)/.25];}
function initFuel(){let stage=0,p=1,auto=false,frame=0,last=0,destroyed=false,view=document.getElementById('initialview').dataset.initial;const canvas=document.getElementById('fuel'),play=document.getElementById('play'),circuit=document.getElementById('circuit'),reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;
document.getElementById('stages').innerHTML=stageNames.map((s,i)=>`<button class="secondary" data-stage="${i}">${i+1} · ${s}</button>`).join('');
function detail(){document.querySelectorAll('[data-stage]').forEach(b=>{b.className=Number(b.dataset.stage)===stage?'selected':'secondary';b.setAttribute('aria-pressed',String(Number(b.dataset.stage)===stage));});document.querySelectorAll('[data-view]').forEach(b=>{b.className=b.dataset.view===view?'selected':'secondary';b.setAttribute('aria-pressed',String(b.dataset.view===view));});document.getElementById('reaction').innerHTML=circuit.checked?'<strong>Stromkreis offen</strong><p>Kein dauerhafter Elektronenfluss, kein fortlaufender Stoffumsatz. Das Modell zeigt wieder die Edukte.</p>':`<strong>${descriptions[stage][0]}</strong><p>${descriptions[stage][1]}</p>`;play.textContent=auto?'Pause':'Ablauf abspielen';canvas.setAttribute('aria-label',`${view==='overview'?'Gesamtansicht':view==='anode'?'Vergrößerte Anode':'Vergrößerte Kathode'}: ${descriptions[stage][0]}. ${descriptions[stage][1]}`);}
const draw=setupCanvas('fuel',(c,w)=>{const s=circuit.checked?0:stage,q=reduced?1:p;if(view==='overview')overview(c,w,s,q);else if(view==='anode')anode(c,w,s,q);else cathode(c,w,s,q);});
function overview(c,w,s,q){const L=w*.24,R=w*.76,M=w*.5,mem=Math.min(95,w*.2),ys=[193,228,263,298];const mg=c.createLinearGradient(M-mem/2,0,M+mem/2,0);mg.addColorStop(0,'#bed9e9');mg.addColorStop(.5,'#e3f3fc');mg.addColorStop(1,'#bed9e9');c.fillStyle=mg;c.fillRect(M-mem/2,153,mem,173);electrode(c,L-10,153,20,173,'right');electrode(c,R-10,153,20,173,'left');text(c,'Anode −',L,120);text(c,'Kathode +',R,120);text(c,'Pt-Katalysator',L,143,'center',12);text(c,'Pt-Katalysator',R,143,'center',12);text(c,'PEM',M,352);text(c,'H⁺ →',M,373);path(c,[[L,153],[L,65],[R,65],[R,153]],'#54798f',3);c.clearRect(M-23,42,46,46);c.strokeStyle='#54798f';c.lineWidth=2;c.beginPath();c.arc(M,65,20,0,Math.PI*2);c.stroke();text(c,'Verbraucher',M,25);if(s===2&&!circuit.checked){c.fillStyle='#d8edb8';c.beginPath();c.arc(M,65,15,0,Math.PI*2);c.fill();}if(circuit.checked){c.clearRect(L-5,90,10,27);path(c,[[L,91],[L+18,105]],'#54798f');}
if(s===0){pair(c,L-38,207,'H');pair(c,L-38,277,'H');pair(c,R+32,242,'O');text(c,'2 H₂',L-36,348);text(c,'O₂',R+32,348);}else if(s===1){oxidize(c,L-38,[207,277],13,L+25,L,ys,q,false);pair(c,R+32,242,'O');}else if(s===2){ys.forEach((y,i)=>{sphere(c,L+25+(R-L-50)*q,y,'H','+');const [x,ey]=wirePoint(L,R,y,q);sphere(c,x+(i-1.5)*5,ey,'e','e⁻',8);});pair(c,R+32,242,'O');}else if(s===3){ys.forEach(y=>sphere(c,R-26,y,'H','+'));oxideStep(c,R,R+Math.min(52,w*.12),ys,q,false);text(c,q>.78?'2 O²⁻ an der Kathode':'O₂ → Kathode',R+18,349);}else{protonateOxide(c,R-26,R+15,[207,279],ys,q,false);text(c,q>.78?'2 H₂O':'je 2 H⁺ + O²⁻',R+15,349);}}
function anode(c,w,s,q){const E=w*.60,memX=w*.81;electrode(c,E-12,125,25,202);c.fillStyle='#d3e8f4';c.fillRect(memX,125,w-memX,202);text(c,'Anode −',E,104);text(c,'PEM',memX+(w-memX)/2,353);text(c,'Platin-Katalysator (Pt)',E,353);text(c,'H₂-Zufuhr',w*.24,104);arrow(c,E,125,E,55,C.el);text(c,'e⁻ zum Leiter',w*.32,30);arrow(c,E+28,311,memX+12,311,C.hyd);
if(s===0){pair(c,w*.28,185,'H',true);pair(c,w*.28,270,'H',true);text(c,'H: 0',w*.28,353);}else if(s===1){oxidize(c,w*.28,[185,270],22,E+29,E,[158,203,248,293],q,true);text(c,'H: 0 → +I',w*.4,375);}else{const ys=[158,203,248,293];ys.forEach((y,i)=>{const advance=s===1?0:s===2?q:1;sphere(c,E+29+(memX-E-5)*advance,y,'H','+',16);sphere(c,E+(i-1.5)*5,y-(y-62)*advance,'e','e⁻',9);});text(c,'4 H⁺ · H: +I',w*.4,375);}}
function cathode(c,w,s,q){const E=w*.43,ys=[155,200,255,300],ox=w*.72;c.fillStyle='#d3e8f4';c.fillRect(0,125,w*.15,202);electrode(c,E-12,125,25,202,'left');text(c,'PEM',w*.08,355);text(c,'Kathode +',E,102);text(c,'O₂-Zufuhr',ox,102);text(c,'Platin-Katalysator (Pt)',E,379);arrow(c,w*.17,320,E-23,320,C.hyd);text(c,'H⁺ →',w*.26,348);arrow(c,E+27,55,E+27,118,C.el);text(c,'e⁻ vom Leiter',w*.54,30);
if(s<2){pair(c,ox,230,'O',true);text(c,'O: 0',ox,355);}else if(s===2){ys.forEach((y,i)=>{sphere(c,w*.12+(E-w*.12-28)*q,y,'H','+',16);sphere(c,E+(i%2?4:-4)*(1-q),60+(y-60)*q,'e','e⁻',9);});pair(c,ox,230,'O',true);text(c,'O: 0',ox,355);}else if(s===3){ys.forEach(y=>sphere(c,E-28,y,'H','+',16));oxideStep(c,E,ox,ys,q);text(c,q>.78?'2 O²⁻ an der Kathode':'O₂ bewegt sich zur Kathode',E+105,355);}else{protonateOxide(c,E-28,E+24,[183,271],ys,q);text(c,q>.78?'2 H₂O · O: −II':'je 2 H⁺ + O²⁻',E+105,355);}}
function oxideStep(c,E,sourceX,ys,q,zoom=true){const oys=zoom?[183,271]:[207,279],d=zoom?22:13,or=zoom?23:16,er=zoom?9:7,surfaceX=E+(zoom?24:15),startY=zoom?230:243,move=Math.min(1,q/.72),charge=Math.max(0,(q-.55)/.45);if(move<.94){c.globalAlpha=.7;arrow(c,sourceX-d-10,startY,surfaceX+d+8,startY,C.oxy);c.globalAlpha=1;}ys.forEach((y,i)=>{c.globalAlpha=1-charge;sphere(c,E+(i%2?4:-4),y,'e','e⁻',er);c.globalAlpha=1;});for(let k=0;k<2;k++){const startX=sourceX+(k?d:-d),x=startX*(1-move)+surfaceX*move,y=startY*(1-move)+oys[k]*move;sphere(c,x,y,'O',charge>.55?'2−':'O',or);}if(move<1)path(c,[[sourceX-d,startY],[sourceX+d,startY]],'#637e90',(zoom?4:3)*(1-move));}
function protonateOxide(c,startH,ox,oys,ys,q,zoom=true){const d=zoom?24:15,or=zoom?23:16,hr=zoom?16:12;oys.forEach((oy,k)=>{sphere(c,ox,oy,'O',q<.75?'2−':'O',or);for(let j=0;j<2;j++){const i=k*2+j,hx=startH*(1-q)+(ox+(j?d:-d))*q,hy=ys[i]*(1-q)+(oy+d*.8)*q;path(c,[[ox,oy],[hx,hy]],'#637e90',q*(zoom?4:3));sphere(c,hx,hy,'H',q<1?'+':'H',hr);}});}
function water(c,ox,oys,startH,ys,startE,q,zoom){const d=zoom?24:15,or=zoom?23:16,hr=zoom?16:12;oys.forEach((oy,k)=>{sphere(c,ox,oy,'O','O',or);for(let j=0;j<2;j++){const i=k*2+j,hx=startH*(1-q)+(ox+(j?d:-d))*q,hy=ys[i]*(1-q)+(oy+d*.8)*q;path(c,[[ox,oy],[hx,hy]],'#637e90',q*(zoom?4:3));sphere(c,hx,hy,'H',q<1?'+':'H',hr);c.globalAlpha=1-q;sphere(c,startE*(1-q)+(ox+(j?-7:7))*q,ys[i]*(1-q)+oy*q,'e','e⁻',zoom?14:12);c.globalAlpha=1;}});}
function tick(now){if(destroyed)return;const dt=last?Math.min(now-last,80):0;last=now;if(auto&&!circuit.checked){p+=dt/2300;if(p>=1){p=1;if(stage<4){stage++;p=0;detail();}else{auto=false;detail();}}}draw();if(auto)frame=requestAnimationFrame(tick);}
function setStage(i){cancelAnimationFrame(frame);auto=false;stage=i;p=(i===1||i===2||i===3||i===4)&&!reduced?0:1;last=0;detail();draw();if((i===1||i===2||i===3||i===4)&&!circuit.checked&&!reduced){const start=performance.now();function animate(now){if(destroyed)return;p=Math.min(1,(now-start)/2000);draw();if(p<1)frame=requestAnimationFrame(animate);}frame=requestAnimationFrame(animate);}}
function setView(v){view=v;detail();draw();}
document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>setView(b.dataset.view));canvas.onclick=e=>{if(view!=='overview')return;const rect=canvas.getBoundingClientRect(),x=e.clientX-rect.left,y=e.clientY-rect.top,w=rect.width;if(y>=145&&y<=333){if(Math.abs(x-w*.24)<30)setView('anode');else if(Math.abs(x-w*.76)<30)setView('cathode');}};canvas.onmousemove=e=>{const r=canvas.getBoundingClientRect(),x=e.clientX-r.left,y=e.clientY-r.top;canvas.style.cursor=view==='overview'&&y>145&&y<333&&(Math.abs(x-r.width*.24)<30||Math.abs(x-r.width*.76)<30)?'zoom-in':'default';};
document.querySelectorAll('[data-stage]').forEach(b=>b.onclick=()=>setStage(Number(b.dataset.stage)));play.onclick=()=>{cancelAnimationFrame(frame);if(circuit.checked)return;auto=!auto;if(auto){if(stage===4){stage=0;p=0;}last=0;frame=requestAnimationFrame(tick);}detail();};document.getElementById('restart').onclick=()=>setStage(0);circuit.onchange=()=>{auto=false;cancelAnimationFrame(frame);stage=0;p=1;detail();draw();};const prior=dispose;dispose=()=>{destroyed=true;cancelAnimationFrame(frame);prior();};detail();}

function initCatalystAnimation(){const canvas=document.getElementById('catcanvas'),ctx=canvas.getContext('2d');let stage=0,p=1,frame=0,destroyed=false,w=700;canvas.style.height='300px';function paint(){ctx.clearRect(0,0,w,300);const surfaceY=225,g=ctx.createLinearGradient(0,surfaceY,w,surfaceY);g.addColorStop(0,'#28485d');g.addColorStop(.5,'#93a9b6');g.addColorStop(1,'#28485d');ctx.fillStyle=g;ctx.fillRect(w*.16,surfaceY,w*.68,24);for(let i=0;i<7;i++){const x=w*.2+i*w*.1;ctx.fillStyle='#607f91';ctx.beginPath();ctx.arc(x,surfaceY+12,13,0,Math.PI*2);ctx.fill();ctx.fillStyle='#fff';ctx.font='11px system-ui';ctx.textAlign='center';ctx.fillText('Pt',x,surfaceY+16);}text(ctx,'Platin-Katalysator (feste Phase)',w*.5,292);const center=w*.5;if(stage===0){const y=65+(surfaceY-105)*p;pair(ctx,center,y,'H',true);arrow(ctx,center,y+30,center,surfaceY-28,C.hyd);}else if(stage===1){const spread=22+42*p;sphere(ctx,center-spread,surfaceY-22,'H','H',18);sphere(ctx,center+spread,surfaceY-22,'H','H',18);if(p<1)path(ctx,[[center-spread,surfaceY-22],[center+spread,surfaceY-22]],'#637e90',4*(1-p));text(ctx,'Anlagerung und Trennung der H–H-Bindung',center,45);}else if(stage===2){for(let i=0;i<2;i++){const x=center+(i?64:-64);sphere(ctx,x,surfaceY-22,'H','+',18);sphere(ctx,x,surfaceY+6+i*11,'e','e⁻',12);arrow(ctx,x,surfaceY-3,x,surfaceY+3+i*11,C.el);}text(ctx,'Elektronenabgabe: H → H⁺ + e⁻',center,45);}else{for(let i=0;i<2;i++){const sx=center+(i?64:-64),hy=surfaceY-22-105*p,ey=surfaceY+6+i*11,ex=sx+120*p;arrow(ctx,sx,surfaceY-42,sx,64,C.hyd);arrow(ctx,sx,ey,center+w*.38,ey,C.el);sphere(ctx,sx,hy,'H','+',18);sphere(ctx,ex,ey,'e','e⁻',13);}text(ctx,'H⁺ → Elektrolyt / PEM',center,38);text(ctx,'e⁻ → Metall und äußerer Stromkreis',center,270);}}
function resize(){const d=devicePixelRatio||1;w=canvas.clientWidth;canvas.width=w*d;canvas.height=300*d;ctx.setTransform(d,0,0,d,0,0);paint();}const ro=new ResizeObserver(resize);ro.observe(canvas);function set(next){cancelAnimationFrame(frame);stage=next;p=matchMedia('(prefers-reduced-motion: reduce)').matches?1:0;const start=performance.now();function animate(now){if(destroyed)return;p=Math.min(1,(now-start)/900);paint();if(p<1)frame=requestAnimationFrame(animate);}frame=requestAnimationFrame(animate);}resize();return{set,destroy(){destroyed=true;cancelAnimationFrame(frame);ro.disconnect();}};}
